name: Build Lisa KSU-Next Kernel
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Env
        run: |
          sudo apt-get update
          sudo apt-get install -y git bc bison flex libssl-dev libelf-dev build-essential
      - name: Clone Kernel
        run: |
          git clone https://github.com/mistrmochov/android_kernel_xiaomi_lisa -b lineage-20 --depth=1 kernel
          cd kernel
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s next
      - name: Setup Clang
        run: |
          git clone https://github.com/kdrag0n/proton-clang --depth=1 --single-branch clang
      - name: Build
        run: |
          cd kernel
          export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
          export ARCH=arm64
          make O=out vendor/lisa_defconfig
          make -j$(nproc) O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1
      - name: Package
        run: |
          git clone https://github.com/osm0sis/AnyKernel3 AnyKernel3
          cp kernel/out/arch/arm64/boot/Image AnyKernel3/
          cd AnyKernel3 && zip -r9 ../Lisa-KSU-Next.zip * -x .git*
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Lisa-KSU-Next-Kernel
          path: Lisa-KSU-Next.zip
